/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author USUARIO
 */
public class Calculadora extends javax.swing.JFrame {
private String cadenanum="", operacion="nula";
private double resultado,primernumero;
    private boolean activado = true,punto=true;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setTitle("CALCULADORA");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonC = new javax.swing.JButton();
        botonRaiz = new javax.swing.JButton();
        botonDivide = new javax.swing.JButton();
        botonCE = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        botonMultiplica = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        botonPorcentaje = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonXcuadrado = new javax.swing.JButton();
        botonPow = new javax.swing.JButton();
        botonPi = new javax.swing.JButton();
        botonmasmenos = new javax.swing.JButton();
        etiquetanumero = new javax.swing.JLabel();
        etiquetamuestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(310, 464));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setPreferredSize(new java.awt.Dimension(298, 330));
        jPanel2.setLayout(new java.awt.GridLayout(6, 4));

        botonC.setBackground(new java.awt.Color(153, 153, 153));
        botonC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonC.setForeground(new java.awt.Color(255, 0, 0));
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        jPanel2.add(botonC);

        botonRaiz.setBackground(new java.awt.Color(153, 153, 153));
        botonRaiz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonRaiz.setText("√ ");
        botonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizActionPerformed(evt);
            }
        });
        jPanel2.add(botonRaiz);

        botonDivide.setBackground(new java.awt.Color(153, 153, 153));
        botonDivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonDivide.setText("/");
        botonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivideActionPerformed(evt);
            }
        });
        jPanel2.add(botonDivide);

        botonCE.setBackground(new java.awt.Color(153, 153, 153));
        botonCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonCE.setForeground(new java.awt.Color(255, 0, 0));
        botonCE.setText("CE");
        botonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCEActionPerformed(evt);
            }
        });
        jPanel2.add(botonCE);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("7");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("8");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("9");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        botonMultiplica.setBackground(new java.awt.Color(153, 153, 153));
        botonMultiplica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonMultiplica.setText("x");
        botonMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicaActionPerformed(evt);
            }
        });
        jPanel2.add(botonMultiplica);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("4");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("5");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("6");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        botonResta.setBackground(new java.awt.Color(153, 153, 153));
        botonResta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        jPanel2.add(botonResta);

        jButton12.setBackground(new java.awt.Color(102, 102, 102));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("1");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton13.setBackground(new java.awt.Color(102, 102, 102));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton13.setText("2");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);

        jButton14.setBackground(new java.awt.Color(102, 102, 102));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton14.setText("3");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);

        botonSuma.setBackground(new java.awt.Color(153, 153, 153));
        botonSuma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonSuma.setText("+");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        jPanel2.add(botonSuma);

        botonPorcentaje.setBackground(new java.awt.Color(153, 153, 153));
        botonPorcentaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonPorcentaje.setText("%");
        botonPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorcentajeActionPerformed(evt);
            }
        });
        jPanel2.add(botonPorcentaje);

        jButton18.setBackground(new java.awt.Color(102, 102, 102));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setText("0");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18);

        botonPunto.setBackground(new java.awt.Color(153, 153, 153));
        botonPunto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        jPanel2.add(botonPunto);

        botonIgual.setBackground(new java.awt.Color(0, 255, 153));
        botonIgual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        jPanel2.add(botonIgual);

        botonXcuadrado.setBackground(new java.awt.Color(153, 153, 153));
        botonXcuadrado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonXcuadrado.setText("x^2");
        botonXcuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonXcuadradoActionPerformed(evt);
            }
        });
        jPanel2.add(botonXcuadrado);

        botonPow.setBackground(new java.awt.Color(153, 153, 153));
        botonPow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonPow.setText("x^y");
        botonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPowActionPerformed(evt);
            }
        });
        jPanel2.add(botonPow);

        botonPi.setBackground(new java.awt.Color(153, 153, 153));
        botonPi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonPi.setText("π");
        botonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPiActionPerformed(evt);
            }
        });
        jPanel2.add(botonPi);

        botonmasmenos.setBackground(new java.awt.Color(153, 153, 153));
        botonmasmenos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonmasmenos.setText("+-");
        botonmasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmasmenosActionPerformed(evt);
            }
        });
        jPanel2.add(botonmasmenos);

        etiquetanumero.setBackground(new java.awt.Color(204, 255, 255));
        etiquetanumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetanumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetanumero.setText("0");

        etiquetamuestra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiquetamuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetamuestra.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetamuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(etiquetanumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetamuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetanumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "7";
        } else {
            cadenanum += "7";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "8";
        } else {
            cadenanum += "8";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "9";
        } else {
            cadenanum += "9";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "4";
        } else {
            cadenanum += "4";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "5";
        } else {
            cadenanum += "5";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "6";
        } else {
            cadenanum += "6";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "1";
        } else {
            cadenanum += "1";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora      
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "2";
        } else {
            cadenanum += "2";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "3";
        } else {
            cadenanum += "3";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "0";
        } else {
            cadenanum += "0";
        }
        etiquetanumero.setText(cadenanum);
        activado = true; //para seguir utilizando la calculadora      
    }//GEN-LAST:event_jButton18ActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        if (activado == true) {
            primernumero = Double.parseDouble(cadenanum);
            etiquetamuestra.setText(cadenanum + "+");
            cadenanum = "";
            operacion = "sumar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
       double pi=3.141592;
        Double segundonumero;      
        if (operacion.equals("nula")) {
            etiquetanumero.setText(cadenanum);
        }
        else if (operacion.equals("sumar")) {
            segundonumero = Double.parseDouble(cadenanum);
            if ((primernumero == pi) || (segundonumero == pi)) {
                resultado = primernumero + segundonumero;
                etiquetanumero.setText(String.format("% .6f", resultado));
                cadenanum = String.valueOf(resultado);
                operacion = "nula";
            } else {
                resultado = primernumero + segundonumero;
                etiquetanumero.setText(String.format("% .2f", resultado));
                cadenanum = String.valueOf(resultado);
                operacion = "nula";
            }
        }
        
        else if (operacion.equals("restar")) {
            segundonumero = Double.parseDouble(cadenanum);
            if ((primernumero == pi) || (segundonumero == pi)) {
                resultado = primernumero - segundonumero;
                etiquetanumero.setText(String.format("%.6f", resultado));
                cadenanum = String.valueOf(resultado);
                operacion = "nula";
            } else {
                resultado = primernumero - segundonumero;
                etiquetanumero.setText(String.format("%.2f", resultado));
                cadenanum = String.valueOf(resultado);
                operacion = "nula";
            }
        }
        
        else if (operacion.equals("multiplicar")) {
            segundonumero = Double.parseDouble(cadenanum);
            if ((primernumero == pi) || (segundonumero == pi)) {
                resultado = primernumero * segundonumero;
                etiquetanumero.setText(String.format("%.6f", resultado));
                cadenanum = String.valueOf(resultado);
                operacion = "nula";
            } else {
                resultado = primernumero * segundonumero;
                etiquetanumero.setText(String.format("%.2f", resultado));
                cadenanum = String.valueOf(resultado);
                operacion = "nula";
            }
        }
           
        else if (operacion.equals("porcentaje")) {
            segundonumero = Double.parseDouble(cadenanum);
            resultado = primernumero * 0.01 * segundonumero;
            etiquetanumero.setText(String.format("%.2f", resultado));
            cadenanum = String.valueOf(resultado);
            operacion = "nula";

        }
        else if (operacion.equals("pow")) {
            segundonumero=Double.parseDouble(cadenanum);
            resultado=Math.pow(primernumero,segundonumero);
            etiquetanumero.setText(String.format("%.2f", resultado));
            cadenanum=String.valueOf(resultado);
            operacion="nula" ;         
        }  
                     
         else if (operacion.equals("dividir")) {
            segundonumero = Double.parseDouble(cadenanum);
            if ((primernumero == pi) || (segundonumero == pi)) {
                if (segundonumero == 0) {
                    etiquetanumero.setText("indeterminado");
                } else {
                    resultado = primernumero / segundonumero;
                    etiquetanumero.setText(String.format("%.6f", resultado));
                    cadenanum = String.valueOf(resultado);
                    operacion = "nula";
                }
            } else {
                if (segundonumero == 0) {
                    etiquetanumero.setText("indeterminado");
                } else {
                    resultado = primernumero / segundonumero;
                    etiquetanumero.setText(String.format("%.2f", resultado));
                    cadenanum = String.valueOf(resultado);
                    operacion = "nula";
                }
            }
        }     
        etiquetamuestra.setText("");
        activado =true;
        punto=false;
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
         if (activado==true) {
            primernumero=Double.parseDouble(cadenanum);
            etiquetamuestra.setText( cadenanum+"-");
            cadenanum="";
            operacion="restar";
            activado=false;
            punto=true;
        }
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicaActionPerformed
        if (activado == true) {
            primernumero = Double.parseDouble(cadenanum);
            etiquetamuestra.setText(cadenanum + "x");
            cadenanum = "";
            operacion = "multiplicar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonMultiplicaActionPerformed

    private void botonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivideActionPerformed
        if (activado == true) {
            primernumero = Double.parseDouble(cadenanum);
            etiquetamuestra.setText(cadenanum + "÷");
            cadenanum = "";
            operacion = "dividir";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonDivideActionPerformed

    private void botonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizActionPerformed
        primernumero = Double.parseDouble(cadenanum);
        etiquetamuestra.setText("√(" + cadenanum + ")");
        resultado = Math.sqrt(primernumero);
        etiquetanumero.setText(String.format("%.2f", resultado));
        cadenanum = String.valueOf(resultado);
        punto = true;
    }//GEN-LAST:event_botonRaizActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if (punto==true) {
            if (cadenanum.equals("")) {
                cadenanum="0.";
            } else {
                cadenanum+=".";
            } 
            etiquetanumero.setText(cadenanum);
            punto =false;
        } 
        
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonmasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmasmenosActionPerformed
        // TODO add your handling code here:
        if (cadenanum.charAt(0) != '-') {
            cadenanum = "-" + cadenanum;
        } else {
            cadenanum = cadenanum.substring(1, cadenanum.length());
        }
        etiquetanumero.setText(cadenanum);
    }//GEN-LAST:event_botonmasmenosActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        // TODO add your handling code here:
        etiquetamuestra.setText("");
        etiquetanumero.setText("0");
        cadenanum="";
        operacion="nula";
        activado= true;
        punto= true;
    }//GEN-LAST:event_botonCActionPerformed

    private void botonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCEActionPerformed
        int tamaño = cadenanum.length();
        if (tamaño > 0) {
            if (tamaño == 1) {
                cadenanum = "0";
            } else {
                cadenanum = cadenanum.substring(0, cadenanum.length() - 1);
            }
            etiquetanumero.setText(cadenanum);
        }
    }//GEN-LAST:event_botonCEActionPerformed

    private void botonXcuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonXcuadradoActionPerformed
        primernumero = Double.parseDouble(cadenanum);
        etiquetamuestra.setText(primernumero + "^2");
        resultado = primernumero * primernumero;
        etiquetanumero.setText(String.format("%.2f", resultado));
        cadenanum = String.valueOf(resultado);
        punto = true;
    }//GEN-LAST:event_botonXcuadradoActionPerformed

    private void botonPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorcentajeActionPerformed
        if (activado == true) {
            primernumero = Double.parseDouble(cadenanum);
            etiquetamuestra.setText(cadenanum + "%");
            cadenanum = "";
            operacion = "porcentaje";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonPorcentajeActionPerformed

    private void botonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPowActionPerformed
        if (activado == true) {
            primernumero = Double.parseDouble(cadenanum);
            etiquetamuestra.setText(cadenanum + "^");
            cadenanum = "";
            operacion = "pow";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonPowActionPerformed

    private void botonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPiActionPerformed
        if (etiquetanumero.getText().equals("0")) {
            cadenanum = "3.141592";
        } else {
            cadenanum += "3.141592";
        }
        etiquetanumero.setText(cadenanum);
        activado = true;
    }//GEN-LAST:event_botonPiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonCE;
    private javax.swing.JButton botonDivide;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplica;
    private javax.swing.JButton botonPi;
    private javax.swing.JButton botonPorcentaje;
    private javax.swing.JButton botonPow;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaiz;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSuma;
    private javax.swing.JButton botonXcuadrado;
    private javax.swing.JButton botonmasmenos;
    private javax.swing.JLabel etiquetamuestra;
    private javax.swing.JLabel etiquetanumero;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
